# -*- coding: utf-8 -*-
"""inventel_finetuning_clean.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oXWZcVkb1fHeKoAYKNR1BQlCEMFVmh2M

## 1. Install Dependencies
"""

# Commented out IPython magic to ensure Python compatibility.
# Install Pytorch & other libraries
# %pip install torch tensorboard

# Install Hugging Face libraries
# %pip install transformers datasets accelerate evaluate trl protobuf sentencepiece

# COMMENT IN: if you are running on a GPU that supports BF16 data type and flash attn, such as NVIDIA L4 or NVIDIA A100
#% pip install flash-attn

"""## 2. Autentikasi Hugging Face"""

from google.colab import userdata
from huggingface_hub import login

# Login into Hugging Face Hub
hf_token = userdata.get('HF_TOKEN')
login(hf_token)

"""## 3. Load Base Model"""

from transformers import AutoTokenizer, AutoModelForCausalLM

gemma_model = "google/functiongemma-270m-it"
base_model = AutoModelForCausalLM.from_pretrained(
    gemma_model,
    device_map="auto",
    attn_implementation="eager",
    dtype="auto")
tokenizer = AutoTokenizer.from_pretrained(gemma_model)

print(f"Device: {base_model.device}")
print(f"DType:  {base_model.dtype}")

"""## 4. Load Dataset"""

import json
from random import randint
from datasets import load_dataset
from huggingface_hub import hf_hub_download

data_file = hf_hub_download(
    repo_id="ferdianfariza/functiongemma-finetuned",
    filename="dataset_final.jsonl",
    repo_type="dataset"
)
dataset = load_dataset("text", data_files=data_file, encoding="utf-8")["train"].shuffle(seed=42)

print(f"Total rows: {len(dataset)}")
print(f"\nSample:")
print(json.dumps(json.loads(dataset[randint(0, len(dataset) - 1)]["text"]), indent=2))

"""## 5. Proses Dataset

Format dataset ke prompt-completion split. Model hanya dilatih pada bagian `completion` (`completion_only_loss=True`) bukan seluruh sequence, sehingga lebih efisien.
"""

def apply_format(sample):
    template_inputs = json.loads(sample["text"])

    prompt_and_completion = tokenizer.apply_chat_template(
        template_inputs["messages"],
        tools=template_inputs["tools"],
        tokenize=False,
        add_generation_prompt=False
    )

    prompt = tokenizer.apply_chat_template(
        template_inputs["messages"][:-1],
        tools=template_inputs["tools"],
        tokenize=False,
        add_generation_prompt=True
    )

    completion = prompt_and_completion[len(prompt):]

    return {
        "prompt": prompt,
        "completion": completion,
        "split": template_inputs["metadata"],
        "text": sample["text"],
    }

processed_dataset = dataset.map(apply_format)

# Cek panjang token terpanjang untuk set max_length
longest = max(processed_dataset, key=lambda x: len(x["prompt"] + x["completion"]))
longest_token_count = len(tokenizer.tokenize(longest["prompt"] + longest["completion"]))
max_token_count = longest_token_count + 100

print(f"Longest example : {longest_token_count} tokens")
print(f"max_token_count : {max_token_count}")

train_dataset = processed_dataset.filter(lambda x: x["split"] == "train")
eval_dataset  = processed_dataset.filter(lambda x: x["split"] == "eval")

print(f"\nTrain : {len(train_dataset)} rows")
print(f"Eval  : {len(eval_dataset)} rows")

"""## 6. Test Base Model (Sebelum Fine-tuning)"""

from transformers import pipeline

pipe = pipeline("text-generation", model=gemma_model, tokenizer=tokenizer, device_map="auto")

user_prompt = "Carikan stok item Meja Informa"
tools = json.loads(dataset[0]["text"])["tools"]

messages = [
    {"role": "developer", "content": "You are an inventory warehouse assistant. Answer user questions by calling the appropriate function. Only call a function when needed."},
    {"role": "user", "content": user_prompt}
]

prompt = tokenizer.apply_chat_template(
    messages,
    tools=tools,
    tokenize=False,
    add_generation_prompt=True
)

output = pipe(prompt, max_new_tokens=max_token_count)
model_output = output[0]["generated_text"][len(prompt):].strip()

print(f"Prompt : {user_prompt}")
print(f"Output : {model_output}")

"""## 7. Konfigurasi Training

| Parameter | Nilai | Alasan |
|---|---|---|
| `num_train_epochs` | `10` | Dataset kecil (240 rows), butuh lebih banyak epoch |
| `learning_rate` | `1e-5` | Lebih konservatif, cocok untuk full fine-tune |
| `lr_scheduler_type` | `cosine` | Lebih smooth convergence dibanding constant |
| `logging_steps` | `5` | Dataset kecil ~60 steps/epoch, log tiap 5 steps |
| `eval_steps` | `10` | Eval lebih sering untuk monitor overfitting |
| `completion_only_loss` | `True` | Hanya train pada assistant turn, bukan seluruh prompt |
| `bf16` | `True` | Mixed precision untuk efisiensi memori |
"""

import torch
from transformers import AutoModelForCausalLM
from trl import SFTConfig

SEED       = 42
output_dir = "/kaggle/working/functiongemma-inventel"

base_model = AutoModelForCausalLM.from_pretrained(
    gemma_model,
    device_map="auto",
    dtype=torch.bfloat16,
    attn_implementation="eager"
)
base_model.config.pad_token_id = tokenizer.pad_token_id

args = SFTConfig(
    # Output
    output_dir=output_dir,

    # Training loop
    num_train_epochs=10,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=32,
    gradient_checkpointing=True,

    # Optimizer
    optim="adamw_torch_fused",
    learning_rate=1e-5,
    lr_scheduler_type="cosine",

    # Precision
    bf16=True,

    # Sequence
    max_length=max_token_count,
    packing=False,
    completion_only_loss=True,

    # Logging & Eval
    logging_strategy="steps",
    logging_steps=5,
    eval_strategy="no",
    eval_steps=10,
    save_strategy="epoch",

    # Reproducibility
    seed=SEED,
    data_seed=SEED,

    report_to="none",
)

print("✅ Training configured")

"""## 8. Training"""

from trl import SFTTrainer

trainer = SFTTrainer(
    model=base_model,
    args=args,
    train_dataset=train_dataset,
    # eval_dataset=eval_dataset,
)

print("🚀 Starting fine-tuning...")
trainer.train()

trainer.save_model(output_dir)
tokenizer.save_pretrained(output_dir)

print(f"\n✅ Model saved to {output_dir}")
print(trainer.state.log_history[-5:])

"""## 9. Training Loss"""

import matplotlib.pyplot as plt

log_history = trainer.state.log_history

train_steps  = [x["step"]  for x in log_history if "loss" in x]
train_losses = [x["loss"]  for x in log_history if "loss" in x]
eval_steps   = [x["step"]  for x in log_history if "eval_loss" in x]
eval_losses  = [x["eval_loss"] for x in log_history if "eval_loss" in x]

plt.figure(figsize=(10, 5))
plt.plot(train_steps, train_losses, label="Train Loss", alpha=0.8)
if eval_losses:
    plt.plot(eval_steps, eval_losses, label="Eval Loss", marker="o", linewidth=2)
plt.xlabel("Step")
plt.ylabel("Loss")
plt.title(f"FunctionGemma Inventel Fine-tuning | lr=1e-5, epochs=10, seed={SEED}")
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig("/kaggle/working/training_loss.png", dpi=150)
plt.show()

"""## 10. Evaluasi Model"""

import re
import pandas as pd
from transformers import pipeline
from transformers.pipelines.pt_utils import KeyDataset

def extract_function_call(model_output):
    results = []
    call_pattern = r"<start_function_call>(.*?)<end_function_call>"
    raw_calls = re.findall(call_pattern, model_output, re.DOTALL)

    for raw_call in raw_calls:
        if not raw_call.strip().startswith("call:"):
            continue
        try:
            pre_brace, args_segment = raw_call.split("{", 1)
            function_name = pre_brace.replace("call:", "").strip()
            args_content = args_segment.strip().rstrip("}")
            arguments = {}
            arg_pattern = r"(?P<key>[^:,]*?):<escape>(?P<value>.*?)<escape>"
            for match in re.finditer(arg_pattern, args_content, re.DOTALL):
                arguments[match.group("key").strip()] = match.group("value")
            results.append({"function": {"name": function_name, "arguments": arguments}})
        except ValueError:
            continue
    return results

def extract_text(model_output):
    if not model_output or model_output.startswith("<start_function_call>"):
        return None
    return model_output.replace("<end_of_turn>", "").strip()

def get_eval_logs(dataset, pipe):
    logs = []
    for i, output in enumerate(pipe(KeyDataset(dataset, "prompt"), batch_size=1)):
        messages      = json.loads(dataset[i]["text"])["messages"]
        input_prompt  = dataset[i]["prompt"]
        model_output  = output[0]["generated_text"][len(input_prompt):].strip()

        logs.append({
            "user":        messages[1]["content"],
            "target_fc":   messages[2].get("tool_calls", []),
            "target_text": messages[2].get("content"),
            "output_fc":   extract_function_call(model_output),
            "output_text": extract_text(model_output),
        })

        if (i + 1) % 10 == 0:
            print(f"  Progress: {i + 1}/{len(dataset)}")
    return logs

def get_scored_data_frame(dataset, pipe):
    logs    = get_eval_logs(dataset, pipe)
    logs_df = pd.DataFrame.from_records(logs)

    scored = pd.DataFrame()
    scored["user"]             = logs_df["user"]
    scored["target_names"]     = logs_df["target_fc"].apply(lambda x: [fc["function"]["name"] for fc in x] if x else [])
    scored["output_names"]     = logs_df["output_fc"].apply(lambda x: [fc["function"]["name"] for fc in x] if x else [])
    scored["target_arguments"] = logs_df["target_fc"].apply(lambda x: [dict(sorted(fc["function"]["arguments"].items())) for fc in x] if x else [])
    scored["output_arguments"] = logs_df["output_fc"].apply(lambda x: [dict(sorted(fc["function"]["arguments"].items())) for fc in x] if x else [])
    scored["target_text"]      = logs_df["target_text"]
    scored["output_text"]      = logs_df["output_text"]
    scored["correct_names"]    = scored["target_names"] == scored["output_names"]
    scored["correct_arguments"]= scored["target_arguments"] == scored["output_arguments"]
    scored["correct"]          = scored["correct_names"] & scored["correct_arguments"]
    return scored

def review(scored):
    mask = (scored["target_names"] != scored["output_names"]) | (scored["target_arguments"] != scored["output_arguments"])
    for idx, row in scored[mask].iterrows():
        print(f"Sample #{idx}")
        print(f"  User    : {row['user']}")
        print(f"  Expected: {row['target_names']} | {row['target_arguments']}")
        print(f"  Actual  : {row['output_names']} | {row['output_arguments']}")
        print("---")

print("✅ Eval helpers ready")

"""### Eval Base Model"""

base_scored = get_scored_data_frame(
    eval_dataset,
    pipeline(
        "text-generation",
        model=gemma_model,
        device_map="auto",
        do_sample=False,
    )
)

print(f"Base model score: {base_scored['correct'].mean():.2%}")
base_scored

"""### Eval Fine-tuned Model"""

from transformers import AutoModelForCausalLM, AutoTokenizer

trained_model = AutoModelForCausalLM.from_pretrained(output_dir, device_map="auto")
trained_tokenizer = AutoTokenizer.from_pretrained(output_dir)

trained_scored = get_scored_data_frame(
    eval_dataset,
    pipeline(
        "text-generation",
        model=trained_model,
        tokenizer=trained_tokenizer,
        do_sample=False,
    )
)

print(f"Fine-tuned model score: {trained_scored['correct'].mean():.2%}")
trained_scored

"""### Perbandingan & Review Kesalahan"""

print(f"Base model score      : {base_scored['correct'].mean():.2%}")
print(f"Fine-tuned model score: {trained_scored['correct'].mean():.2%}")

print("\n--- Incorrect predictions ---")
review(trained_scored)

import matplotlib.pyplot as plt
import numpy as np

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# ── Chart 1: Overall comparison ────────────────────────────────────────────
models = ['Base Model', 'Fine-tuned Model']
correct = [27.69, 69.23]
incorrect = [72.31, 30.77]

x = np.arange(len(models))
width = 0.5

axes[0].bar(x, correct, width, label='Correct', color='#1D9E75')
axes[0].bar(x, incorrect, width, bottom=correct, label='Incorrect', color='#B4B2A9')
axes[0].set_xticks(x)
axes[0].set_xticklabels(models)
axes[0].set_ylabel('Percentage (%)')
axes[0].set_title('Overall Accuracy: Base vs Fine-tuned')
axes[0].set_ylim(0, 100)
axes[0].legend()
axes[0].grid(axis='y', alpha=0.3)

for i, (c, inc) in enumerate(zip(correct, incorrect)):
    axes[0].text(i, c / 2, f'{c:.1f}%', ha='center', va='center', color='white', fontweight='bold')
    axes[0].text(i, c + inc / 2, f'{inc:.1f}%', ha='center', va='center', color='white', fontweight='bold')

# ── Chart 2: Error breakdown fine-tuned ────────────────────────────────────
categories = [
    'getMostBorrowedItems\n(argumen kosong)',
    'getAvailableItems vs\ngetItemInfo',
    'Out-of-scope\ntidak dikenali',
    'getItemHistoryLocation\nvs getItemLocation',
]
errors = [5, 4, 4, 3]
y = np.arange(len(categories))

axes[1].barh(y, errors, color='#E24B4A', height=0.5)
axes[1].set_yticks(y)
axes[1].set_yticklabels(categories, fontsize=9)
axes[1].set_xlabel('Jumlah Error')
axes[1].set_title('Breakdown Error Fine-tuned Model (20 errors)')
axes[1].grid(axis='x', alpha=0.3)

for i, v in enumerate(errors):
    axes[1].text(v + 0.05, i, str(v), va='center', fontweight='bold')

plt.suptitle(
    f'FunctionGemma 270M Inventel | Base: 27.69% → Fine-tuned: 69.23% (+41.54%)',
    fontsize=11, y=1.02
)
plt.tight_layout()
plt.savefig('/kaggle/working/evaluation_comparison.png', dpi=150, bbox_inches='tight')
plt.show()

"""## 11. Push ke Hugging Face Hub"""

from huggingface_hub import whoami

username   = whoami()["name"]
hf_repo_id = f"{username}/functiongemma-270m-it-finetuned-inventel"

trained_model.push_to_hub(hf_repo_id, commit_message="Fine-tuned FunctionGemma 270M for Inventel")
trained_tokenizer.push_to_hub(hf_repo_id)

print(f"✅ Model pushed to: https://huggingface.co/{hf_repo_id}")